### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by lukesnowden** [thephpleague/glide-laravel#4]
Are there any parameters to compress the output or quality as its doesn't seem to be documented anywhere?

**Comment by lukesnowden** [comment]
Never Mind, https://github.com/thephpleague/glide/blob/master/src/Manipulators/Encode.php#L70 gave me a hint.

```javascript
return $this->server->getImageResponse( "{$basename}",  [
	'w' 	=> $predefinedSize['width'],
	'h' 	=> $predefinedSize['height'],
	'fit' 	=> $predefinedSize['method'],
	'q'     => 70
] );
```

**Comment by reinink** [comment]
Yep, see this page: http://glide.thephpleague.com/1.0/api/encode/
