### ISSUE TITLE
Laravel 7 compatibility

### ISSUE THREAD

**Issue by ifox** [thephpleague/glide-laravel#6]
Hi @reinink!

Thanks for your work on Glide, it's a godsend for our Laravel CMS, https://github.com/area17/twill. We are about to release Laravel 7 support but are blocked by this package until https://github.com/thephpleague/glide-symfony/pull/7 is resolved.

Let us know if you think this is something you are able to release soon, otherwise we'll see if we can depend on Glide directly in the meantime.

Thank you!

**Comment by reinink** [comment]
Done! 💪

**Comment by ifox** [comment]
You're the best @reinink, thank you so much!
